client_id = "1cf4ca06ee6cd8a6caf6c67c32e6db65"
name = "SQUAD21 ORDER MANAGEMENT"
application_url = "https://mardi-fiddle-implode.ngrok-free.dev"
embedded = false

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request"]
uri = "https://mardi-fiddle-implode.ngrok-free.dev/api/webhooks/shopify/compliance/customers-data-request"

[[webhooks.subscriptions]]
compliance_topics = ["customers/redact"]
uri = "https://mardi-fiddle-implode.ngrok-free.dev/api/webhooks/shopify/compliance/customers-redact"

[[webhooks.subscriptions]]
compliance_topics = ["shop/redact"]
uri = "https://mardi-fiddle-implode.ngrok-free.dev/api/webhooks/shopify/compliance/shop-redact"

[access_scopes]
scopes = "read_customers,read_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://mardi-fiddle-implode.ngrok-free.dev/api/shopify/oauth/callback"
]